package com.solostack.resqgrid.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;

// Tells JPA that this Java class represents a database table
@Entity

// Specifies the exact table name in MySQL
@Table(name = "supply_requests")
public class SupplyRequest {

    // Primary key of the table
    @Id

    // ID will be automatically generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Camp ID is required and cannot be blank
    @NotBlank
    private String campId;

    // Number of people must be provided and must be greater than 0
    @NotNull
    @Positive
    private Integer peopleAffected;

    // Quantity can be 0 or greater
    // 0 is valid because a camp may not need this particular supply
    @NotNull
    @PositiveOrZero
    private Integer waterQuantity;

    @NotNull
    @PositiveOrZero
    private Integer foodQuantity;

    @NotNull
    @PositiveOrZero
    private Integer medicineQuantity;

    @NotNull
    @PositiveOrZero
    private Integer blanketQuantity;

    // Stores the enum value as text such as NORMAL, HIGH, CRITICAL
    @NotNull
    @Enumerated(EnumType.STRING)
    private Priority priority;

    // Stores the request status as text such as PENDING or ACCEPTED
    @Enumerated(EnumType.STRING)
    private RequestStatus status;


    // No-argument constructor
    // JPA requires this constructor
    public SupplyRequest() {
    }


    // Parameterized constructor
    // Useful when we want to create a SupplyRequest object with values
    public SupplyRequest(
            String campId,
            Integer peopleAffected,
            Integer waterQuantity,
            Integer foodQuantity,
            Integer medicineQuantity,
            Integer blanketQuantity,
            Priority priority,
            RequestStatus status) {

        this.campId = campId;
        this.peopleAffected = peopleAffected;
        this.waterQuantity = waterQuantity;
        this.foodQuantity = foodQuantity;
        this.medicineQuantity = medicineQuantity;
        this.blanketQuantity = blanketQuantity;
        this.priority = priority;
        this.status = status;
    }


    // Getter and Setter for ID
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    // Getter and Setter for Camp ID
    public String getCampId() {
        return campId;
    }

    public void setCampId(String campId) {
        this.campId = campId;
    }


    // Getter and Setter for people affected
    public Integer getPeopleAffected() {
        return peopleAffected;
    }

    public void setPeopleAffected(Integer peopleAffected) {
        this.peopleAffected = peopleAffected;
    }


    // Getter and Setter for water quantity
    public Integer getWaterQuantity() {
        return waterQuantity;
    }

    public void setWaterQuantity(Integer waterQuantity) {
        this.waterQuantity = waterQuantity;
    }


    // Getter and Setter for food quantity
    public Integer getFoodQuantity() {
        return foodQuantity;
    }

    public void setFoodQuantity(Integer foodQuantity) {
        this.foodQuantity = foodQuantity;
    }


    // Getter and Setter for medicine quantity
    public Integer getMedicineQuantity() {
        return medicineQuantity;
    }

    public void setMedicineQuantity(Integer medicineQuantity) {
        this.medicineQuantity = medicineQuantity;
    }


    // Getter and Setter for blanket quantity
    public Integer getBlanketQuantity() {
        return blanketQuantity;
    }

    public void setBlanketQuantity(Integer blanketQuantity) {
        this.blanketQuantity = blanketQuantity;
    }


    // Getter and Setter for priority
    public Priority getPriority() {
        return priority;
    }

    public void setPriority(Priority priority) {
        this.priority = priority;
    }


    // Getter and Setter for status
    public RequestStatus getStatus() {
        return status;
    }

    public void setStatus(RequestStatus status) {
        this.status = status;
    }
}