package com.solostack.resqgrid.dto;

import com.solostack.resqgrid.entity.Priority;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;

// DTO used when a camp worker creates a new supply request.
// Important:
// This class contains ONLY the data that the client is allowed to send.
// We do NOT include id or status here.
//
// id     -> generated by the database
// status -> controlled by our backend
public class SupplyRequestCreateRequest {

    // Camp identifier is required.
    @NotBlank(message = "Camp ID is required")
    private String campId;

    // Number of people affected must be greater than 0.
    @NotNull(message = "People affected is required")
    @Positive(message = "People affected must be greater than 0")
    private Integer peopleAffected;

    // Supply quantities can be 0, but cannot be negative.
    @NotNull(message = "Water quantity is required")
    @PositiveOrZero(message = "Water quantity cannot be negative")
    private Integer waterQuantity;

    @NotNull(message = "Food quantity is required")
    @PositiveOrZero(message = "Food quantity cannot be negative")
    private Integer foodQuantity;

    @NotNull(message = "Medicine quantity is required")
    @PositiveOrZero(message = "Medicine quantity cannot be negative")
    private Integer medicineQuantity;

    @NotNull(message = "Blanket quantity is required")
    @PositiveOrZero(message = "Blanket quantity cannot be negative")
    private Integer blanketQuantity;

    // Priority is required.
    @NotNull(message = "Priority is required")
    private Priority priority;

    // No-argument constructor.
    // Jackson uses this constructor when converting JSON into Java object.
    public SupplyRequestCreateRequest() {
    }

    // Getters and Setters

    public String getCampId() {
        return campId;
    }

    public void setCampId(String campId) {
        this.campId = campId;
    }

    public Integer getPeopleAffected() {
        return peopleAffected;
    }

    public void setPeopleAffected(Integer peopleAffected) {
        this.peopleAffected = peopleAffected;
    }

    public Integer getWaterQuantity() {
        return waterQuantity;
    }

    public void setWaterQuantity(Integer waterQuantity) {
        this.waterQuantity = waterQuantity;
    }

    public Integer getFoodQuantity() {
        return foodQuantity;
    }

    public void setFoodQuantity(Integer foodQuantity) {
        this.foodQuantity = foodQuantity;
    }

    public Integer getMedicineQuantity() {
        return medicineQuantity;
    }

    public void setMedicineQuantity(Integer medicineQuantity) {
        this.medicineQuantity = medicineQuantity;
    }

    public Integer getBlanketQuantity() {
        return blanketQuantity;
    }

    public void setBlanketQuantity(Integer blanketQuantity) {
        this.blanketQuantity = blanketQuantity;
    }

    public Priority getPriority() {
        return priority;
    }

    public void setPriority(Priority priority) {
        this.priority = priority;
    }
}