package com.solostack.resqgrid.exception;

import org.springframework.http.HttpStatus;

import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestControllerAdvice;


// Handles exceptions from our Controllers globally.
//
// Instead of writing error handling inside every Controller,
// we keep it in one central class.
@RestControllerAdvice
public class GlobalExceptionHandler {


    // Handles validation errors.
    //
    // Example:
    // peopleAffected = -500
    //
    // @Positive validation fails
    // and this method handles that error.
    @ExceptionHandler(MethodArgumentNotValidException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public ErrorResponse handleValidationException(
            MethodArgumentNotValidException exception) {

        // Get the message generated by the validation annotation
        String message = exception.getBindingResult()
                .getFieldError()
                .getDefaultMessage();

        // Return our custom error response
        return new ErrorResponse(message, 400);
    }


    // Handles cases where a requested resource doesn't exist.
    //
    // Example:
    // GET /api/requests/999
    //
    // If ID 999 doesn't exist,
    // ResourceNotFoundException is thrown.
    @ExceptionHandler(ResourceNotFoundException.class)
    @ResponseStatus(HttpStatus.NOT_FOUND)
    public ErrorResponse handleResourceNotFoundException(
            ResourceNotFoundException exception) {

        // Get the message from our custom exception
        return new ErrorResponse(
                exception.getMessage(),
                404
        );
    }

    // Handles invalid status transitions.
//
// Example:
// PENDING → DELIVERED
//
// This transition is not allowed,
// so we return HTTP 400 Bad Request.
    @ExceptionHandler(InvalidStatusTransitionException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public ErrorResponse handleInvalidStatusTransition(
            InvalidStatusTransitionException exception) {
        // Return our custom error response
        return new ErrorResponse(
                exception.getMessage(),
                400
        );
    }
}